courses/base/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import CourseResource, CategoryResource
from tastypie.api import Api

course_resource = CourseResource()
category_resource = CategoryResource()

api = Api(api_name='v1')
api.register(course_resource)
api.register(category_resource)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include(api.urls)),
]

courses/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'


urlpatterns = [
    path('', views.index, name='index'),
    path('course/<int:course_id>', views.single_course, name='single_course')
]

courses/api/models.py
from shop.models import Category, Course
from tastypie.resources import ModelResource
#from .authentication import CustomAuthentication
#from tastypie.authorization import Authorization

# Create your models here.
class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methodes = ['get']
class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'cources'
        allowed_methodes = ['get', 'post', 'delete']
#        authentication = CustomAuthentication()
#        authorization = Authorization()

courses/shop/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

courses/api/views.py
from django.shortcuts import render

# Create your views here.

courses/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course
# Create your views here.

def index(request):
    courses = Course.objects.all()
    #return HttpResponse(''.join([str(course) + '<br>' for course in courses]))
    #return HttpResponse(courses)
    return render(request, 'shop/courses.html', {'courses': courses})
def single_course(request, course_id):
    #Option(Вариант) 1
    #try:
    #    course = Course.objects.get(pk = course_id)
    #    return render(request, 'single_course.html', {'course': course})
    #except Course.DoesNotExist:
    #   raise Http404()
    #Option(Вариант) 2
    course = get_object_or_404(Course, pk = course_id)
    return render(request, 'shop/single_course.html', {'course': course})

courses/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href= {% url "shop:index" %} class="navbar-brand">Courses Shop</a>
            <span class="navbar-text">
                <a href="/admin/" class="me-2" target="_blank">Admin</a>
                <a href="/api/v1/" target="_blank">API</a>
            </span>
        </div>
    </nav>
    <main class="container">
        {%block content%}
        {% endblock %} 
    </main>

    
</body>
</html>

courses/templates/shop/courses.html
{% extends "base.html" %}
{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td>
                <a href={% url 'shop:single_course' course.id %}>{{ course.title }}</a>
            </td>
            <td>{{ course.category }}</td>
            <td>{{ course.price }}</td>
            <td>{{ course.students_qty }}</td>
            <td><button class="btn btn-primary">Buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

courses/templates/shop/single_course.html
{% extends 'base.html' %}

{% block title%}{{course.title}}{%endblock%}

{% block content %}
<h1 class="mt-2">{{ course.title }}</h1>
<h2>{{ course.category }}</h2>
<p>Price: {{ course.price }}</p>
<p>Students Quantity: {{ course.students_qty }}</p>
<button class="btn btn-primary">Buy</button>
{% endblock %}